**NUMPY For AI and ML**

In [20]:
import numpy as np


Basics

In [21]:
a= np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [22]:
b = np.array([[9,8,7],[6,5,7]])
print(b)

[[9 8 7]
 [6 5 7]]


In [23]:
#Get dimensions
a.ndim

1

In [24]:
#Get shape
b.shape

(2, 3)

In [25]:
#Get type
a.dtype

dtype('int32')

In [26]:
#Get size
a.itemsize
b.itemsize

8

In [27]:
#Get total size
a.nbytes

12

Accessing/Changing specific elements,rows,columns,etc

In [28]:
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
#get specific element [r,c]
c[0,5]

6

In [30]:
#get specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
#get specific column
c[:,2]

array([ 3, 10])

In [32]:
#Getting a little more fancy [startindex:endindex:stepsize]
c[0,1:5:2]

array([2, 4])

In [33]:
c[1,5]=20
print(c)

c[:,2]=[1,2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-D examples


In [34]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
#Get specific element (worik outside in)
d[0,1,1]

4

In [36]:
#replace
d[:,:,1]=[9,9]
print(d)

[[[1 9]
  [3 9]]

 [[5 9]
  [7 9]]]


Initializing Different types of array

In [38]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
#ALl 1s matrix
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
#Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [43]:
#Any other number (full_like)
np.full_like(a,4)

array([4, 4, 4], dtype=int32)

In [47]:
#Random decimal numbwers
np.random.random_sample(a.shape)

array([0.2120365 , 0.79729997, 0.54945751])

In [49]:
#Random Integer Values
np.random.randint(6,7,size=(3,3))#6,7 ke beech mein koi bhi values uthayega

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [50]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [58]:
output = np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
#Be careful while coppying the array
x=np.array([1,2,3])
l=x.copy()
l[0]=100
print(l)

[100   2   3]


Mathematics


In [62]:
a1=np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [66]:
a1+2

array([5, 6, 7, 8])

In [67]:
a1-=2

In [68]:
a1-2

array([-1,  0,  1,  2])

In [69]:
a1*2

array([2, 4, 6, 8])

In [ ]:
#We can use operators just like in Python
#We can use sine cosine etc.


Linear Algebra


In [71]:
t=np.ones((2,3))
print(t)

e=np.full((3,2),2)
print(e)

np.matmul(t,e)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [73]:
t1=np.identity(3)
print(t1)
np.linalg.det(t1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [74]:
#reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

Stats

In [75]:
stats = np.array([[1,2,3],[2,3,4]])
stats

array([[1, 2, 3],
       [2, 3, 4]])

In [76]:
np.min(stats)

1

In [81]:
np.max(stats,axis=1)

array([3, 4])

In [82]:
np.sum(stats,axis=0)

array([3, 5, 7])

Reorganizinf Arrays


In [86]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [89]:
#Vertically Stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [90]:
#Horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous

In [91]:
#Load data from a file
# filedata = np.genfromtxt('name.txt',delimiter=',')
# filedata.astype('int32')
# filedata

In [92]:
#Boolean masking and Advanced Indexing
# filedata>=50
# filedata[filedata>50]

In [94]:
#You can index with a list in numpy
hnm=np.array([1,2,3,4,5,6,7,8,9])
hnm[[1,2,8]]

array([2, 3, 9])

In [95]:
np.any(hnm>3.5)

True

In [96]:
((hnm>3) & (hnm<7))

array([False, False, False,  True,  True,  True, False, False, False])

In [106]:
ques=np.arange(30).reshape(6,5)
ques+=1
print(ques)
des1=ques[2:4,0:2]
print(des1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
